
---
title: IDEPE
output: html_document
---
  
```{r setup, include=FALSE}
pacman::p_load(crosstalk, dplyr, DT, plotly, data.table, ade4, arules, car, caret, corrplot, e1071, forcats, funModeling, ggplot2, mlbench, mltools, randomForest, rattle, tidyverse)

idepe_enem_dt <- fread('https://raw.githubusercontent.com/hugoavmedeiros/ciencia_politica_com_r/master/bases_tratadas/idepe_enem_scolas_2019.csv', dec = ",")

# Dummies
idepe_enem_D <- acm.disjonctif(as.data.frame(idepe_enem_dt$tp_escola))
names(idepe_enem_D) <- c('integral', 'regular', 'semi_integral', 'tecnica')

idepe_enem <- cbind(idepe_enem_dt, idepe_enem_D)

sd <- idepe_enem %>% select(enem, tp_escola, tp_localizacao, idepe) %>% SharedData$new()


```

IDEPE
================================
  # Índice de Desenvolvimento da Educação de Pernambuco IDEPE começou a ser medido em 2008 e é consolidado com base no desempenho do Sistema de Avaliação da Educação Básica de Pernambuco (SAEPE) e na Taxa de Aprovação. O desempenho corresponde à média da performance dos alunos em Língua Portuguesa e Matemática, resultante dos testes elaborados no SAEPE.
  
  
```{r, warning=FALSE, out.width='100%', echo = FALSE, message = FALSE}

filter_slider("enem", "Nota do Enem", sd, ~enem, step=50, width=650)

filter_checkbox("tp_escola", "Tipo de Escola", sd, ~tp_escola, inline = TRUE)

filter_checkbox("tp_localizacao", "Localização", sd, ~tp_localizacao, inline = TRUE)

sd %>% plot_ly(x = ~enem, y = ~idepe)

```

```{r}

sd %>% datatable(
  # Título
  caption = htmltools::tags$caption(
    # estilo do título usando css
    style = 'text-align: center; font-size: 18px; font-weight: bold;',
    'Tabela 1: Base de Dados IDEPE'),
  # nomes das colunas
  #colnames = c('noda do enem', 'Tipo de escola', 'Localização', 'nota idepe'),
  filter = "top",
  # extensões para serem acrescentadas
  extensions = c('Buttons', 'ColReorder', 'Responsive'),
  # as opções configuram efetivamente as extensões
  options = list(
    #
    dom = 'Blfrtip',
    # primeiro vamos configurar os botões, adicionando funcionalidades
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
    # permite ao usuário reordenar as colunas
    colReorder = TRUE,
    # controla quantas linhas serão mostradas por página
    pageLength = 25, 
    # ativa o spinner (indicador de processamento)
    processing = TRUE
  )
) 

```
